### ISSUE TITLE
`dev` branch configuration seems wrong

### ISSUE THREAD

**Issue by sgoggins** [oss-aspen/8Knot#289]
**Describe the bug**
I am getting these errors: 
```
cache_1            | 1:S 18 Mar 2023 20:07:02.150 * Connecting to MASTER 194.38.20.225:8886
cache_1            | 1:S 18 Mar 2023 20:07:02.150 * MASTER <-> REPLICA sync started
cache_1            | 1:S 18 Mar 2023 20:07:02.206 # Error condition on socket for SYNC: Connection refused
query-worker_1     | [2023-03-18 20:07:02,647: CRITICAL/MainProcess] Unrecoverable error: ReadOnlyError("You can't write against a read only replica.")
query-worker_1     | Traceback (most recent call last):
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/worker/worker.py", line 203, in start
query-worker_1     |     self.blueprint.start(self)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/bootsteps.py", line 116, in start
query-worker_1     |     step.start(parent)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/bootsteps.py", line 365, in start
query-worker_1     |     return self.obj.start()
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/worker/consumer/consumer.py", line 332, in start
query-worker_1     |     blueprint.start(self)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/bootsteps.py", line 116, in start
query-worker_1     |     step.start(parent)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/worker/consumer/connection.py", line 21, in start
query-worker_1     |     c.connection = c.connect()
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/celery/worker/consumer/consumer.py", line 430, in connect
query-worker_1     |     conn.transport.register_with_event_loop(conn.connection, self.hub)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/kombu/transport/redis.py", line 1292, in register_with_event_loop
query-worker_1     |     cycle.on_poll_init(loop.poller)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/kombu/transport/redis.py", line 539, in on_poll_init
query-worker_1     |     return channel.qos.restore_visible(
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/kombu/transport/redis.py", line 403, in restore_visible
query-worker_1     |     with Mutex(client, self.unacked_mutex_key,
query-worker_1     |   File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
query-worker_1     |     return next(self.gen)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/kombu/transport/redis.py", line 163, in Mutex
query-worker_1     |     lock_acquired = lock.acquire(blocking=False)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/lock.py", line 207, in acquire
query-worker_1     |     if self.do_acquire(token):
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/lock.py", line 223, in do_acquire
query-worker_1     |     if self.redis.set(self.name, token, nx=True, px=timeout):
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/commands/core.py", line 2220, in set
query-worker_1     |     return self.execute_command("SET", *pieces, **options)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/client.py", line 1238, in execute_command
query-worker_1     |     return conn.retry.call_with_retry(
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
query-worker_1     |     return do()
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/client.py", line 1239, in <lambda>
query-worker_1     |     lambda: self._send_command_parse_response(
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/client.py", line 1215, in _send_command_parse_response
query-worker_1     |     return self.parse_response(conn, command_name, **options)
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/client.py", line 1254, in parse_response
query-worker_1     |     response = connection.read_response()
query-worker_1     |   File "/opt/app-root/lib64/python3.9/site-packages/redis/connection.py", line 839, in read_response
query-worker_1     |     raise response
query-worker_1     | redis.exceptions.ReadOnlyError: You can't write against a read only replica.
8knot_callback-worker_1 exited with code 0
cache_1            | 1:S 18 Mar 2023 20:07:03.155 * Connecting to MASTER 194.38.20.225:8886
cache_1            | 1:S 18 Mar 2023 20:07:03.155 * MASTER <-> REPLICA sync started
cache_1            | 1:S 18 Mar 2023 20:07:03.235 # Error condition on socket for SYNC: Connection refused
cache_1            | 1:S 18 Mar 2023 20:07:04.159 * Connecting to MASTER 194.38.20.225:8886
cache_1            | 1:S 18 Mar 2023 20:07:04.159 * MASTER <-> REPLICA sync started
8knot_query-worker_1 exited with code 0
cache_1            | 1:S 18 Mar 2023 20:07:05.235 # Error condition on socket for SYNC: Connection refused
cache_1            | 1:S 18 Mar 2023 20:07:06.166 * Connecting to MASTER 194.38.20.225:8886
cache_1            | 1:S 18 Mar 2023 20:07:06.166 * MASTER <-> REPLICA sync started
cache_1            | 1:S 18 Mar 2023 20:07:06.244 # Error condition on socket for SYNC: Connection refused
cache_1            | 1:S 18 Mar 2023 20:07:07.171 * Connecting to MASTER 194.38.20.225:8886
cache_1            | 1:S 18 Mar 2023 20:07:07.171 * MASTER <-> REPLICA sync started
cache_1            | 1:S 18 Mar 2023 20:07:07.215 # Error condition on socket for SYNC: Connection refused
cache_1            | 1:S 18 Mar 2023 20:07:08.174 * Connecting to MASTER 194.38.20.225:8886
```

**To Reproduce**
1. Clone repository on an EC2 instance
2. `sudo docker-compose up --build`
3. Wait

**Expected behavior**
I would not expect these errors 

**Additional context**
OS: Ubuntu 22.x on an ec2 instance.

**Comment by sgoggins** [comment]
The latest dev version is working.
