### ISSUE TITLE
389ds/freeipa doesn't exist anymore and breaks directory dropdown

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#627]
Input repo was: 
['https://github.com/389ds/freeipa']

dash.exceptions.LongCallbackError: An error occurred inside a long callback: can only concatenate str (not "NoneType") to str Traceback (most recent call last): File "/opt/app-root/lib64/python3.9/site-packages/dash/long_callback/managers/celery_manager.py", line 157, in run user_callback_output = fn(*maybe_progress, *user_callback_args) File "/opt/app-root/src/pages/codebase/visualizations/contribution_file_heatmap.py", line 203, in directory_dropdown path_slice = repo_id + "-" + repo_path + "/" + repo_name + "/" TypeError: can only concatenate str (not "NoneType") to str

**Comment by cdolfi** [comment]
Thanks for pointing this out, probably another corner case that needs to be handled. Will work on this soon, have a feeling it will be an easy fix

**Comment by cdolfi** [comment]
@JamesKunstle after looking into it https://github.com/389ds/freeipa doesnt actually exist (anymore, I would assume). Not sure how it is in the dropdown/what we should do to prevent this
