### ISSUE TITLE
postgresql cache error

### ISSUE THREAD

**Issue by sgoggins** [oss-aspen/8Knot#654]
**Describe the bug**
- Loading up the app on the public instance of augur, the issue staleness and issues over time graphs fail toload
- The following error is generated on the backend
```
postgres-cache-1    | 2024-03-11 16:42:06.705 GMT [3630] STATEMENT:  INSERT INTO issues_query VALUES (25498,'grimoirelab',33978,350,648121323,'01000cb7-4800-0',NULL,'2020-06-30T12:11:08'::timestamp,NULL),(25498,'grimoirelab',33977,351,648126105,'01000cb7-4800-0',NULL,'2020-06-30T12:18:59'::timestamp,NULL),(25498,'grimoirelab',33976,352,648234326,'0100f374-8f00-0',NULL,'2020-06-30T14:41:32'::timestamp,'2020-07-13T12:25:57'::timestamp),(25481,'grimoirelab-elk',32773,907,649027087,'010025af-9700-0',NULL,'2020-07-01T14:26:53'::timestamp,'2023-10-11T16:09:01'::timestamp),(25507,'wg-risk',32689,102,649305848,'0100a0d0-b500-0',NULL,'2020-07-01T20:41:01'::timestamp,'2020-08-07T18:50:25'::timestamp),(25506,'wg-value',32616,104,650025557,'01008739-4500-0',NULL,'2020-07-02T15:31:14'::timestamp,'2020-09-10T15:07:41'::timestamp),(25528,'wg-ospo',32344,5,1654424765,

...

06054,'0102296d-9f00-0',NULL,'2024-03-08T08:08:12'::timestamp,NULL) ON CONFLICT DO NOTHING
worker-query-1      | [2024-03-11 16:42:06,708: CRITICAL/ForkPoolWorker-1] issues_query_POSTGRES ERROR: integer out of range
worker-query-1      | 
worker-query-1      | [2024-03-11 16:42:06,711: ERROR/ForkPoolWorker-1] Task queries.issues_query.issues_query[17c290ac-7536-49fb-8d47-686021a763de] raised unexpected: Exception(NumericValueOutOfRange('integer out of range\n'))
worker-query-1      | Traceback (most recent call last):
worker-query-1      |   File "/opt/app-root/src/cache_manager/cache_facade.py", line 188, in caching_wrapper
worker-query-1      |     cache_query_results(
worker-query-1      |   File "/opt/app-root/src/cache_manager/cache_facade.py", line 91, in cache_query_results
worker-query-1      |     execute_values(
worker-query-1      |   File "/opt/app-root/lib64/python3.9/site-packages/psycopg2/extras.py", line 1299, in execute_values
worker-query-1      |     cur.execute(b''.join(parts))
worker-query-1      | psycopg2.errors.NumericValueOutOfRange: integer out of range
worker-query-1      | 
worker-query-1      | 
worker-query-1      | During handling of the above exception, another exception occurred:
worker-query-1      | 
worker-query-1      | Traceback (most recent call last):
worker-query-1      |   File "/opt/app-root/lib64/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
worker-query-1      |     R = retval = fun(*args, **kwargs)
worker-query-1      |   File "/opt/app-root/lib64/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
worker-query-1      |     return self.run(*args, **kwargs)
worker-query-1      |   File "/opt/app-root/lib64/python3.9/site-packages/celery/app/autoretry.py", line 54, in run
worker-query-1      |     ret = task.retry(exc=exc, **retry_kwargs)
worker-query-1      |   File "/opt/app-root/lib64/python3.9/site-packages/celery/app/task.py", line 717, in retry
worker-query-1      |     raise_with_context(exc)
worker-query-1      |   File "/opt/app-root/lib64/python3.9/site-packages/celery/app/autoretry.py", line 34, in run
worker-query-1      |     return task._orig_run(*args, **kwargs)
worker-query-1      |   File "/opt/app-root/src/queries/issues_query.py", line 62, in issues_query
worker-query-1      |     cf.caching_wrapper(
worker-query-1      |   File "/opt/app-root/src/cache_manager/cache_facade.py", line 199, in caching_wrapper
worker-query-1      |     raise Exception(e)
worker-query-1      | Exception: integer out of range
worker-query-1      | 
worker-callback-3   | [2024-03-11 16:42:06,869: WARNING/ForkPoolWorker-1] ISSUES OVER TIME - WAITING ON DATA TO BECOME AVAILABLE
worker-callback-11  | [2024-03-11 16:42:06,869: WARNING/ForkPoolWorker-1] ISSUES STALENESS - WAITING ON DATA TO BECOME AVAILABLE
worker-callback-1   | [2024-03-11 16:42:07,321: WARNING/ForkPoolWorker-1] [('queries.issues_query.issues_query', 'FAILURE')]
```

**To Reproduce**
1. go to https://metrix.chaoss.io to see the frontend error
2. start 8Knot up against an app pointed to https://ai.chaoss.io to see the example backend errors.

**Comment by JamesKunstle** [comment]
fixed on dev
